spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled:true
jwt:
  secret: ${JWT_SECRET}
route:
  path:
    secured:
      - "/api/v1/users/**"
    allowed:
      - "/api/v1/users/register"
      - "/api/v1/users/login"
service:
  user-service-uri: "http://user-service-svc"