spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres-svc/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret: ${JWT_SECRET}
  expiration: PT15M